# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
from grpc_service import opinion_service_pb2 as opinion__service__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in opinion_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OpinionAnalysisServiceStub(object):
    """Opinion Analysis Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ClassifyOpinion = channel.unary_unary(
                '/opinion_service.OpinionAnalysisService/ClassifyOpinion',
                request_serializer=opinion__service__pb2.ClassifyRequest.SerializeToString,
                response_deserializer=opinion__service__pb2.ClassifyResponse.FromString,
                _registered_method=True)
        self.ClassifyBatch = channel.unary_unary(
                '/opinion_service.OpinionAnalysisService/ClassifyBatch',
                request_serializer=opinion__service__pb2.BatchClassifyRequest.SerializeToString,
                response_deserializer=opinion__service__pb2.BatchClassifyResponse.FromString,
                _registered_method=True)
        self.MatchOpinionsToTopic = channel.unary_unary(
                '/opinion_service.OpinionAnalysisService/MatchOpinionsToTopic',
                request_serializer=opinion__service__pb2.MatchRequest.SerializeToString,
                response_deserializer=opinion__service__pb2.MatchResponse.FromString,
                _registered_method=True)
        self.GenerateConclusion = channel.unary_unary(
                '/opinion_service.OpinionAnalysisService/GenerateConclusion',
                request_serializer=opinion__service__pb2.ConclusionRequest.SerializeToString,
                response_deserializer=opinion__service__pb2.ConclusionResponse.FromString,
                _registered_method=True)
        self.AnalyzeTopic = channel.unary_unary(
                '/opinion_service.OpinionAnalysisService/AnalyzeTopic',
                request_serializer=opinion__service__pb2.TopicAnalysisRequest.SerializeToString,
                response_deserializer=opinion__service__pb2.TopicAnalysisResponse.FromString,
                _registered_method=True)


class OpinionAnalysisServiceServicer(object):
    """Opinion Analysis Service
    """

    def ClassifyOpinion(self, request, context):
        """Classify a single opinion
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClassifyBatch(self, request, context):
        """Classify multiple opinions in batch
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MatchOpinionsToTopic(self, request, context):
        """Match opinions to a topic
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateConclusion(self, request, context):
        """Generate conclusion for a topic with opinions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeTopic(self, request, context):
        """Full pipeline: match + classify + conclude
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OpinionAnalysisServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ClassifyOpinion': grpc.unary_unary_rpc_method_handler(
                    servicer.ClassifyOpinion,
                    request_deserializer=opinion__service__pb2.ClassifyRequest.FromString,
                    response_serializer=opinion__service__pb2.ClassifyResponse.SerializeToString,
            ),
            'ClassifyBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.ClassifyBatch,
                    request_deserializer=opinion__service__pb2.BatchClassifyRequest.FromString,
                    response_serializer=opinion__service__pb2.BatchClassifyResponse.SerializeToString,
            ),
            'MatchOpinionsToTopic': grpc.unary_unary_rpc_method_handler(
                    servicer.MatchOpinionsToTopic,
                    request_deserializer=opinion__service__pb2.MatchRequest.FromString,
                    response_serializer=opinion__service__pb2.MatchResponse.SerializeToString,
            ),
            'GenerateConclusion': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateConclusion,
                    request_deserializer=opinion__service__pb2.ConclusionRequest.FromString,
                    response_serializer=opinion__service__pb2.ConclusionResponse.SerializeToString,
            ),
            'AnalyzeTopic': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeTopic,
                    request_deserializer=opinion__service__pb2.TopicAnalysisRequest.FromString,
                    response_serializer=opinion__service__pb2.TopicAnalysisResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'opinion_service.OpinionAnalysisService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('opinion_service.OpinionAnalysisService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OpinionAnalysisService(object):
    """Opinion Analysis Service
    """

    @staticmethod
    def ClassifyOpinion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/opinion_service.OpinionAnalysisService/ClassifyOpinion',
            opinion__service__pb2.ClassifyRequest.SerializeToString,
            opinion__service__pb2.ClassifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClassifyBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/opinion_service.OpinionAnalysisService/ClassifyBatch',
            opinion__service__pb2.BatchClassifyRequest.SerializeToString,
            opinion__service__pb2.BatchClassifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MatchOpinionsToTopic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/opinion_service.OpinionAnalysisService/MatchOpinionsToTopic',
            opinion__service__pb2.MatchRequest.SerializeToString,
            opinion__service__pb2.MatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateConclusion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/opinion_service.OpinionAnalysisService/GenerateConclusion',
            opinion__service__pb2.ConclusionRequest.SerializeToString,
            opinion__service__pb2.ConclusionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeTopic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/opinion_service.OpinionAnalysisService/AnalyzeTopic',
            opinion__service__pb2.TopicAnalysisRequest.SerializeToString,
            opinion__service__pb2.TopicAnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
